#most unexported functions are stored here

#strWrap and/or toString below would allow you to not have the super run-on lines. need to
#figure out how to implement them.

#this really random line of code makes R not throw a warning with respect to the non-
#standard foreach loops in some of the functions
globalVariables("i")

absQueryPaster <- function(loc.code)
{
	out <- paste("with T1 as (select sub_out.SUB_ID, sub_out.GROUP_ID, sub_out.CREATION_DT, sub_out.PROTOCOL_ID, sub_out.LOC_ID, loc.NAME, sub_out.USER_ID, loc.SUBNATIONAL1_CODE, loc.SUBNATIONAL2_CODE, loc.LATITUDE, loc.LONGITUDE, sub_out.DURATION_HRS, sub_out.ALL_OBS_REPORTED, sub_out.OBS_DT, sub_out.EFFORT_HRS_ATLEAST, sub_out.EFFORT_HRS_ATMOST, sub_out.EFFORT_DISTANCE_KM, sub_out.EFFORT_DISTANCE_KM_ATLEAST, sub_out.EFFORT_DISTANCE_KM_ATMOST, sub_out.NUM_OBSERVERS from sub_out JOIN LOC on (sub_out.loc_id = loc.loc_id) where LOC.SUBNATIONAL1_CODE IN (",
					loc.code,
					")) select T1.LOC_ID, T1.SUBNATIONAL1_CODE, T1.SUBNATIONAL2_CODE, T1.LATITUDE, T1.LONGITUDE, T1.SUB_ID, T1.SUB_ID as OBS_ID, T1.GROUP_ID, CREATION_DT, T1.PROTOCOL_ID, protocol.DESCRIPTION as PROTOCOL_NAME, T1.USER_ID, T1.DURATION_HRS, T1.ALL_OBS_REPORTED, T1.OBS_DT, T1.EFFORT_HRS_ATLEAST, T1.EFFORT_HRS_ATMOST, T1.EFFORT_DISTANCE_KM, T1.EFFORT_DISTANCE_KM_ATLEAST, T1.EFFORT_DISTANCE_KM_ATMOST, T1.NUM_OBSERVERS from t1 join protocol on (t1.protocol_id = protocol.protocol_id)",
					sep="'")
    out
}

#strWrap and/or toString below would allow you to not have the super run-on lines. need to
#figure out how to implement them.

allQueryPaster <- function(loc.code)
{
	out <- paste("with SubObs as (select SUB_OUT.LOC_ID AS LocIDfromSub, SUB_OUT.SUB_ID, OBS_OUT.OBS_ID, SUB_OUT.GROUP_ID, SUB_OUT.CREATION_DT, SUB_OUT.PROTOCOL_ID, SUB_OUT.LOC_ID, SUB_OUT.USER_ID, SUB_OUT.DURATION_HRS, SUB_OUT.ALL_OBS_REPORTED, SUB_OUT.OBS_DT, SUB_OUT.EFFORT_HRS_ATLEAST, SUB_OUT.EFFORT_HRS_ATMOST, SUB_OUT.EFFORT_DISTANCE_KM, SUB_OUT.EFFORT_DISTANCE_KM_ATLEAST, SUB_OUT.EFFORT_DISTANCE_KM_ATMOST, SUB_OUT.NUM_OBSERVERS, OBS_OUT.ORIG_SPECIES_CODE, OBS_OUT.SCI_NAME, OBS_OUT.HOW_MANY_ATLEAST, OBS_OUT.HOW_MANY_ATMOST, OBS_OUT.REVIEWED, OBS_OUT.VALID from SUB_OUT join OBS_OUT on (SUB_OUT.SUB_ID = OBS_OUT.SUB_ID) where SUB_OUT.SUBNATIONAL1_CODE_S IN (",
			loc.code,
		")) select LOC.LOC_ID, LOC.SUBNATIONAL1_CODE, LOC.SUBNATIONAL2_CODE, LOC.LATITUDE, LOC.LONGITUDE, SubObs.SUB_ID, SubObs.OBS_ID, SubObs.GROUP_ID, SubObs.CREATION_DT, protocol.PROTOCOL_ID, protocol.DESCRIPTION as PROTOCOL_NAME, SubObs.USER_ID, SubObs.DURATION_HRS, SubObs.ALL_OBS_REPORTED, SubObs.OBS_DT, SubObs.EFFORT_HRS_ATLEAST, SubObs.EFFORT_HRS_ATMOST, SubObs.EFFORT_DISTANCE_KM, SubObs.EFFORT_DISTANCE_KM_ATLEAST, SubObs.EFFORT_DISTANCE_KM_ATMOST, SubObs.NUM_OBSERVERS, SubObs.ORIG_SPECIES_CODE, SubObs.SCI_NAME, SubObs.HOW_MANY_ATLEAST, SubObs.HOW_MANY_ATMOST, SubObs.REVIEWED, SubObs.VALID from SubObs join LOC on (SubObs.LocIDfromSub = LOC.LOC_ID) join protocol on (SubObs.protocol_id = protocol.protocol_id)",
					sep="'")
}

#strWrap and/or toString below would allow you to not have the super run-on lines. need to
#figure out how to implement them.

spQueryPaster <- function(sp.codes)
{
	if(length(sp.codes) == 1)
	{
		out <- paste("with SubObs as (select SUB_OUT.LOC_ID AS LocIDfromSub, SUB_OUT.SUB_ID, OBS_OUT.OBS_ID, SUB_OUT.GROUP_ID, SUB_OUT.CREATION_DT, SUB_OUT.PROTOCOL_ID, SUB_OUT.LOC_ID, SUB_OUT.USER_ID, SUB_OUT.DURATION_HRS, SUB_OUT.ALL_OBS_REPORTED, OBS_OUT.COMMENTS, SUB_OUT.OBS_DT, SUB_OUT.EFFORT_HRS_ATLEAST, SUB_OUT.EFFORT_HRS_ATMOST, SUB_OUT.EFFORT_DISTANCE_KM, SUB_OUT.EFFORT_DISTANCE_KM_ATLEAST, SUB_OUT.EFFORT_DISTANCE_KM_ATMOST, SUB_OUT.NUM_OBSERVERS, OBS_OUT.ORIG_SPECIES_CODE, OBS_OUT.SCI_NAME, OBS_OUT.HOW_MANY_ATLEAST, OBS_OUT.HOW_MANY_ATMOST, OBS_OUT.REVIEWED, OBS_OUT.VALID from SUB_OUT join OBS_OUT on (SUB_OUT.SUB_ID = OBS_OUT.SUB_ID) where OBS_OUT.ORIG_SPECIES_CODE IN (",
					sp.codes,
					")) select LOC.LOC_ID, LOC.SUBNATIONAL1_CODE, LOC.SUBNATIONAL2_CODE, LOC.LATITUDE, LOC.LONGITUDE, SubObs.SUB_ID, SubObs.OBS_ID, SubObs.GROUP_ID, SubObs.CREATION_DT, protocol.PROTOCOL_ID, protocol.DESCRIPTION as PROTOCOL_NAME, SubObs.USER_ID, SubObs.DURATION_HRS, SubObs.ALL_OBS_REPORTED, SubObs.OBS_DT, SubObs.EFFORT_HRS_ATLEAST, SubObs.EFFORT_HRS_ATMOST, SubObs.EFFORT_DISTANCE_KM, SubObs.EFFORT_DISTANCE_KM_ATLEAST, SubObs.EFFORT_DISTANCE_KM_ATMOST, SubObs.NUM_OBSERVERS, SubObs.ORIG_SPECIES_CODE, SubObs.SCI_NAME, SubObs.HOW_MANY_ATLEAST, SubObs.HOW_MANY_ATMOST, SubObs.REVIEWED, SubObs.COMMENTS, SubObs.VALID from SubObs join LOC on (SubObs.LocIDfromSub = LOC.LOC_ID) join protocol on (SubObs.protocol_id = protocol.protocol_id)",
					sep="'")
    }
    
    else if(length(sp.codes) > 1)
	{
		out <- paste("with SubObs as (select SUB_OUT.LOC_ID AS LocIDfromSub, SUB_OUT.SUB_ID, OBS_OUT.OBS_ID, SUB_OUT.GROUP_ID, SUB_OUT.CREATION_DT, SUB_OUT.PROTOCOL_ID, SUB_OUT.LOC_ID, SUB_OUT.USER_ID, SUB_OUT.DURATION_HRS, SUB_OUT.ALL_OBS_REPORTED, OBS_OUT.COMMENTS, SUB_OUT.OBS_DT, SUB_OUT.EFFORT_HRS_ATLEAST, SUB_OUT.EFFORT_HRS_ATMOST, SUB_OUT.EFFORT_DISTANCE_KM, SUB_OUT.EFFORT_DISTANCE_KM_ATLEAST, SUB_OUT.EFFORT_DISTANCE_KM_ATMOST, SUB_OUT.NUM_OBSERVERS, OBS_OUT.ORIG_SPECIES_CODE, OBS_OUT.SCI_NAME, OBS_OUT.HOW_MANY_ATLEAST, OBS_OUT.HOW_MANY_ATMOST, OBS_OUT.REVIEWED, OBS_OUT.VALID from SUB_OUT join OBS_OUT on (SUB_OUT.SUB_ID = OBS_OUT.SUB_ID) where OBS_OUT.ORIG_SPECIES_CODE IN (",
					paste(sp.codes, collapse="', '"),
					")) select LOC.LOC_ID, LOC.SUBNATIONAL1_CODE, LOC.SUBNATIONAL2_CODE, LOC.LATITUDE, LOC.LONGITUDE, SubObs.SUB_ID, SubObs.OBS_ID, SubObs.GROUP_ID, SubObs.CREATION_DT, protocol.PROTOCOL_ID, protocol.DESCRIPTION as PROTOCOL_NAME, SubObs.USER_ID, SubObs.DURATION_HRS, SubObs.ALL_OBS_REPORTED, SubObs.OBS_DT, SubObs.EFFORT_HRS_ATLEAST, SubObs.EFFORT_HRS_ATMOST, SubObs.EFFORT_DISTANCE_KM, SubObs.EFFORT_DISTANCE_KM_ATLEAST, SubObs.EFFORT_DISTANCE_KM_ATMOST, SubObs.NUM_OBSERVERS, SubObs.ORIG_SPECIES_CODE, SubObs.SCI_NAME, SubObs.HOW_MANY_ATLEAST, SubObs.HOW_MANY_ATMOST, SubObs.REVIEWED, SubObs.COMMENTS, SubObs.VALID from SubObs join LOC on (SubObs.LocIDfromSub = LOC.LOC_ID) join protocol on (SubObs.protocol_id = protocol.protocol_id)",
					sep="'")
    }
    
    else
    {
    	stop("Something is wrong")
    }
    
    out
}
